//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using System.ServiceModel;

namespace Chat_Library
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class Message
    {
        [DataMember]
        public int MessageId { get; set; }
        [DataMember]
        public string MessageSender { get; set; }
        [DataMember]
        public string MessageContent { get; set; }
    }
}
